import frappe

no_cache = 1

CATEGORIES = [
	("aziende", "🏢", "Registri Aziendali & Corporate"),
	("sanzioni", "🚨", "Sanzioni, PEP & Wanted"),
	("cyber", "⚡", "Cybercrime & Threat Intelligence"),
	("breach", "💧", "Data Breach & Credential Leak"),
	("crypto", "⛓", "Blockchain & Crypto Forensics"),
	("geo", "🌍", "Geolocalizzazione & Satellite"),
	("trasporti", "✈", "Trasporti — Navi & Aerei"),
	("social", "📱", "Social Media & SOCMINT"),
	("immagini", "🖼", "Immagini & Forensics Visuale"),
	("giudiziario", "⚖", "Giudiziario & Penale"),
	("immobili", "🏠", "Immobili & Asset"),
	("media", "📰", "Media, News & Web Archive"),
	("govdata", "🏛", "Open Government Data"),
]

FONTI = [
	# ---------- AZIENDE ----------
	dict(icon="🏛", name="OpenCorporates", domain="opencorporates.com", cat="aziende",
		tags=["aziende", "api"],
		desc="235M+ aziende in 145 giurisdizioni. Ricerca per nome, numero, UBO, direttori. Standard globale per shell company research.",
		methods=[
			("WEB", "Ricerca Web", "opencorporates.com → barra di ricerca → nome azienda o numero → filtra per giurisdizione. Dati base gratuiti senza login.", ""),
			("API", "API REST (500 req/mese gratis)", "Registrati → ottieni API key.",
				"GET https://api.opencorporates.com/v0.4/companies/search?q=petterson+holding&jurisdiction_code=gb&api_token=KEY"),
			("DOWNLOAD", "Bulk Download", "opencorporates.com/info/our-data → dataset CSV scaricabili gratuitamente per alcune giurisdizioni.", ""),
		],
		links=[("Portale", "https://opencorporates.com"), ("API Key", "https://opencorporates.com/api_accounts/new")]),
	dict(icon="🇬🇧", name="Companies House UK", domain="find-and-update.company-information.service.gov.uk", cat="aziende",
		tags=["aziende", "api", "ue"],
		desc="Registro ufficiale UK. Bilanci, atti, PSC/UBO, directors. API gratuita con 600 req/min. Essenziale per entità UK.",
		methods=[
			("WEB", "Portale Web", "Inserisci nome o company number → tab \"Officers\", \"PSC\", \"Filing history\" → download PDF gratuito.", ""),
			("API", "API REST (gratuita, 600 req/min)", "Registrati su developer.company-information.service.gov.uk → crea app → API key.",
				"GET https://api.company-information.service.gov.uk/company/{company_number}/persons-with-significant-control"),
			("DOWNLOAD", "Bulk Data", "developer.company-information.service.gov.uk/guides/bulk-data-files → dataset mensili completi CSV/JSON gratuiti.", ""),
		],
		links=[("Search", "https://find-and-update.company-information.service.gov.uk"), ("API Dev", "https://developer.company-information.service.gov.uk")]),
	dict(icon="🇨🇭", name="Zefix — Registro CH", domain="zefix.ch", cat="aziende",
		tags=["aziende", "api"],
		desc="Registro commerciale svizzero. Tutti i cantoni. API REST pubblica senza autenticazione.",
		methods=[
			("WEB", "Ricerca Web", "zefix.ch → nome/UID/sede → tutti i dati base gratuiti.", ""),
			("API", "API REST (no auth)", "JSON con UID, sede, stato. Docs Swagger disponibili.",
				"GET https://www.zefix.admin.ch/ZefixREST/api/v1/firm.json?name=avondale&languageKey=it"),
		],
		links=[("Zefix", "https://zefix.ch"), ("API", "https://www.zefix.admin.ch/ZefixPublicREST/")]),
	dict(icon="🇺🇸", name="EDGAR — SEC USA", domain="sec.gov/edgar", cat="aziende",
		tags=["aziende", "api", "finanza"],
		desc="Tutti i filing aziende USA quotate: 10-K, 10-Q, 8-K, insider trading, beneficial ownership (13F, 13G).",
		methods=[
			("WEB", "EDGAR Full-Text Search", "efts.sec.gov → ricerca full-text nei documenti SEC. Oppure sec.gov/cgi-bin/browse-edgar → per nome/CIK.", ""),
			("API", "EDGAR Data API (gratuita)", "CIK cercalo su EDGAR. companyfacts per tutti i dati finanziari strutturati.",
				"GET https://data.sec.gov/submissions/CIK0000320193.json\nGET https://data.sec.gov/api/xbrl/companyfacts/CIK{NUM}.json"),
		],
		links=[("EDGAR", "https://www.sec.gov/cgi-bin/browse-edgar"), ("Data API", "https://www.sec.gov/edgar/sec-api-documentation")]),
	dict(icon="💼", name="ICIJ Offshore Leaks", domain="offshoreleaks.icij.org", cat="aziende",
		tags=["aziende", "aml", "finanza"],
		desc="Panama Papers, Pandora Papers, FinCEN Files, HSBC Files, Paradise Papers. 800K+ entità offshore, intermediari, beneficiari.",
		methods=[
			("WEB", "Ricerca Web", "offshoreleaks.icij.org/search → nome persona/azienda → filtra per dataset e paese → visualizza connessioni grafo.", ""),
			("DOWNLOAD", "Download Dataset Completo", "offshoreleaks.icij.org/pages/database → scarica CSV per ogni dataset. Importa in Neo4j o Gephi per analisi grafo avanzata.", ""),
			("API", "Neo4j Graph (locale)", "Importa CSV in Neo4j Desktop → Cypher query:",
				"MATCH (p:Officer)-[r]-(e:Entity) WHERE p.name CONTAINS \"ROSSI\" RETURN p,r,e"),
		],
		links=[("Search", "https://offshoreleaks.icij.org/search"), ("Dataset", "https://offshoreleaks.icij.org/pages/database")]),
	dict(icon="🌐", name="OpenOwnership — Beneficial Ownership", domain="register.openownership.org", cat="aziende",
		tags=["aziende", "aml"],
		desc="Database globale titolari effettivi (UBO). Dati da registri nazionali UK, Ucraina, Danimarca, Armenia e altri.",
		methods=[
			("WEB", "Ricerca Web", "register.openownership.org → cerca persona o azienda → visualizza catena proprietaria completa.", ""),
			("API", "API REST", "BODS (Beneficial Ownership Data Standard) JSON.",
				"GET https://api.bods.openownership.org/entities/?name=company+name"),
			("DOWNLOAD", "Bulk Data", "data.openownership.org → dataset UBO per paese in formato BODS JSON.", ""),
		],
		links=[("Register", "https://register.openownership.org"), ("API", "https://www.openownership.org/en/topics/data-and-technology/")]),
	dict(icon="🇮🇪", name="CRO Ireland Open Data", domain="cro.ie", cat="aziende",
		tags=["aziende", "api", "ue"],
		desc="Registro imprese irlandesi. Open Data Portal con API e bulk download. Dati finanziari inclusi.",
		methods=[
			("WEB", "Ricerca", "cro.ie → nome/numero → documenti, director, UBO.", ""),
			("API", "Open Data API", "opendata.cro.ie → endpoint REST gratuito → dati aziende e bilanci in JSON/XML.", ""),
		],
		links=[("CRO", "https://cro.ie"), ("Open Data", "https://opendata.cro.ie")]),
	dict(icon="🔍", name="OCCRP Aleph", domain="aleph.occrp.org", cat="aziende",
		tags=["aziende", "giudiziario", "media", "api"],
		desc="250+ dataset investigativi: offshore leaks, sanzioni, documenti giudiziari, corporate registries, dati leaked. Standard per giornalismo investigativo globale.",
		methods=[
			("WEB", "Ricerca Full-Text", "aleph.occrp.org → registrati gratis → ricerca full-text su tutti i dataset → filtra per collection/paese/data.", ""),
			("API", "API REST", "Entità cross-dataset. API key gratuita post-registrazione.",
				"GET https://aleph.occrp.org/api/2/entities?q=NAME&schema=Person&api_key=KEY"),
			("DOWNLOAD", "Follow the Money (FtM)", "Libreria Python → import dati OCCRP in grafo → connetti a Maltego o Neo4j.",
				"pip install followthemoney"),
		],
		links=[("Aleph", "https://aleph.occrp.org"), ("API", "https://redocly.github.io/redoc/?url=https://aleph.occrp.org/api/openapi.json")]),

	# ---------- SANZIONI ----------
	dict(icon="🚨", name="OpenSanctions", domain="opensanctions.org", cat="sanzioni",
		tags=["sanzioni", "aml", "api"],
		desc="100+ fonti sanzioni globali + PEP + wanted lists. Aggiornamento giornaliero. API REST. Self-hosted con Docker.",
		methods=[
			("WEB", "Ricerca diretta", "opensanctions.org/search → nome/alias → risultato con sorgente e dataset. Zero registrazione.", ""),
			("API", "API (gratis rate-limited)", "Ottieni API key su opensanctions.org/api.",
				"GET https://api.opensanctions.org/match/default?name=mario+rossi&schema=Person&api_key=KEY"),
			("CLI", "Self-hosted Docker (illimitato gratis)", "API locale senza limiti su http://localhost:8000/match",
				"docker pull ghcr.io/opensanctions/yente:latest\ndocker run -p 8000:8000 yente"),
			("DOWNLOAD", "Download dataset", "opensanctions.org/datasets/default → FtM JSON (1.5GB) → importa in Neo4j o query locale.", ""),
		],
		links=[("Search", "https://www.opensanctions.org/search/"), ("API", "https://www.opensanctions.org/api/"), ("GitHub", "https://github.com/opensanctions/opensanctions")]),
	dict(icon="🏦", name="OFAC SDN List", domain="sanctionssearch.ofac.treas.gov", cat="sanzioni",
		tags=["sanzioni"],
		desc="Lista ufficiale SDN USA (US Treasury). Aggiornata real-time. Sanzioni su persone, entità, navi, aeromobili.",
		methods=[
			("WEB", "Search diretto", "sanctionssearch.ofac.treas.gov → nome → risultato immediato. Nessuna registrazione.", ""),
			("DOWNLOAD", "Download XML/CSV", "XML completo con tutti i record. Aggiornamento automatizzabile con cron.",
				"wget https://www.treasury.gov/ofac/downloads/sdn.xml"),
			("API", "Integra via OpenSanctions", "OpenSanctions include OFAC via API strutturata. Oppure libreria Python:",
				"pip install sanctions-explorer"),
		],
		links=[("Search OFAC", "https://sanctionssearch.ofac.treas.gov"), ("SDN XML", "https://www.treasury.gov/ofac/downloads/sdn.xml")]),
	dict(icon="🇪🇺", name="EU Consolidated Sanctions", domain="sanctionsmap.eu", cat="sanzioni",
		tags=["sanzioni", "api"],
		desc="Lista consolidata sanzioni EU. Persone, entità, settori. XML/CSV scaricabile. API EU SPARQL endpoint.",
		methods=[
			("WEB", "Sanctions Map", "sanctionsmap.eu → ricerca visuale per regimi sanzionatori. Zero registrazione.", ""),
			("DOWNLOAD", "Download XML ufficiale", "",
				"wget \"https://webgate.ec.europa.eu/fsd/fsf/public/files/xmlFullSanctionsList_1_1/content?token=dG9rZW4tMjAxNw\" -O eu_sanctions.xml"),
			("API", "EUR-Lex SPARQL", "Query per regolamento specifico → JSON-LD risultato.",
				"https://publications.europa.eu/webapi/rdf/sparql"),
		],
		links=[("Sanctions Map", "https://sanctionsmap.eu"), ("EU FinSan DB", "https://webgate.ec.europa.eu/fsd/fsf")]),
	dict(icon="🌐", name="UN Security Council List", domain="scsanctions.un.org", cat="sanzioni",
		tags=["sanzioni"],
		desc="Lista consolidata sanzioni ONU (ISIL, Al-Qaeda, Taliban, North Korea, Iran, etc.). XML ufficiale.",
		methods=[
			("WEB", "Ricerca Web", "scsanctions.un.org/search → nome → dettaglio sanzione e regimi applicabili.", ""),
			("DOWNLOAD", "Download XML", "Lista completa in XML aggiornata.",
				"wget https://scsanctions.un.org/resources/xml/en/consolidated.xml"),
		],
		links=[("UN Sanctions", "https://scsanctions.un.org"), ("XML", "https://scsanctions.un.org/resources/xml/en/consolidated.xml")]),

	# ---------- CYBER ----------
	dict(icon="🦠", name="VirusTotal", domain="virustotal.com", cat="cyber",
		tags=["cyber", "api"],
		desc="Analisi malware/URL/IP/domain su 70+ engine. 4 req/min gratuiti. Fondamentale per IOC analysis.",
		methods=[
			("WEB", "Upload/Search Web", "virustotal.com → drag&drop file o incolla URL/IP/hash MD5/SHA256 → report immediato.", ""),
			("API", "API v3 (gratuita 4 req/min)", "Registrati → Account → API Key.",
				"curl --request GET --url \"https://www.virustotal.com/api/v3/ip_addresses/8.8.8.8\" --header \"x-apikey: YOURKEY\""),
			("CLI", "vt-cli (command line)", "",
				"pip install vt-cli\nvt url https://suspicious.site\nvt ip 1.2.3.4\nvt file malware.exe"),
		],
		links=[("VirusTotal", "https://www.virustotal.com"), ("Signup", "https://www.virustotal.com/gui/join-us"), ("API", "https://docs.virustotal.com/reference/overview")]),
	dict(icon="🧪", name="Abuse.ch — MalwareBazaar/ThreatFox", domain="abuse.ch", cat="cyber",
		tags=["cyber", "api"],
		desc="Repository IOC, malware samples, botnet tracker (Feodo), URLhaus, ThreatFox. Community security. Tutto gratuito.",
		methods=[
			("WEB", "MalwareBazaar", "bazaar.abuse.ch → cerca per hash SHA256/MD5/SHA1, tag, firma → download sample gratuito.", ""),
			("API", "API JSON (gratuita)", "Info malware JSON + ThreatFox IOC:",
				"curl -d \"query=get_info&hash=SHA256HASH\" https://mb-api.abuse.ch/api/v1/\ncurl -d '{\"query\":\"search_ioc\",\"search_term\":\"1.2.3.4\"}' https://threatfox-api.abuse.ch/api/v1/"),
			("DOWNLOAD", "Feed automatici", "Feodo IP Blocklist → aggiornato giornalmente. Importa in firewall o SIEM automaticamente.", ""),
		],
		links=[("Abuse.ch", "https://abuse.ch"), ("MalwareBazaar", "https://bazaar.abuse.ch"), ("ThreatFox", "https://threatfox.abuse.ch")]),
	dict(icon="🔬", name="URLscan.io", domain="urlscan.io", cat="cyber",
		tags=["cyber", "api"],
		desc="Scanner URL con screenshot DOM, richieste di rete, verdetto. Rivela phishing, C2, redirect chain. API gratuita.",
		methods=[
			("WEB", "Scan URL", "urlscan.io → incolla URL → \"Scan\" → screenshot, DOM, network calls, IP, certificate, verdetto.", ""),
			("API", "API REST", "Submit scan + search:",
				"curl -X POST \"https://urlscan.io/api/v1/scan/\" -H \"API-Key:KEY\" -H \"Content-Type: application/json\" -d '{\"url\":\"http://suspicious.site\",\"visibility\":\"public\"}'\ncurl \"https://urlscan.io/api/v1/search/?q=domain:phishingsite.com\""),
		],
		links=[("URLscan", "https://urlscan.io"), ("Signup", "https://urlscan.io/user/signup"), ("API", "https://urlscan.io/docs/api/")]),
	dict(icon="🌐", name="Censys — Internet Scanner", domain="censys.io", cat="cyber",
		tags=["cyber", "api"],
		desc="Scanner internet: certificati TLS, porte aperte, banner. Asset discovery infrastruttura. API gratuita limitata.",
		methods=[
			("WEB", "Search Web", "search.censys.io → query tipo: services.port:22 AND location.country:IT → host con SSH in Italia.", ""),
			("API", "API v2 (gratuita 250 req/mese)", "Registrati → Account → API ID+Secret.",
				"curl -u \"API_ID:API_SECRET\" \"https://search.censys.io/api/v2/hosts/search?q=services.port:80+AND+autonomous_system.name:telecom+italia\""),
		],
		links=[("Censys", "https://search.censys.io"), ("Signup", "https://accounts.censys.io/register"), ("API", "https://search.censys.io/api")]),
	dict(icon="💉", name="Pulsedive — Threat Intel", domain="pulsedive.com", cat="cyber",
		tags=["cyber", "api"],
		desc="Piattaforma threat intel community-driven. IOC correlation, IP/domain/URL, feeds. Piano base gratuito.",
		methods=[
			("WEB", "Lookup", "pulsedive.com/explore → inserisci IP/dominio/URL → risk score, tag, linked threats, feeds. Zero login per lookup base.", ""),
			("API", "API (gratis 30 req/min)", "JSON con risk, threats, feeds.",
				"curl \"https://pulsedive.com/api/?indicator=1.2.3.4&pretty=1&key=YOUR_KEY\""),
		],
		links=[("Pulsedive", "https://pulsedive.com"), ("API", "https://pulsedive.com/api/")]),
	dict(icon="📶", name="GreyNoise Community", domain="greynoise.io", cat="cyber",
		tags=["cyber", "api"],
		desc="Distingue rumore internet da attività malevola targetizzata. Riduce falsi positivi SOC. Community gratuito.",
		methods=[
			("WEB", "IP Visualizer", "viz.greynoise.io → inserisci IP → benign/malicious/unknown + contesto.", ""),
			("API", "Community API (gratuita)", "Key gratuita su greynoise.io/signup. JSON con noise/riot/classification.",
				"curl -H \"key: YOUR_API_KEY\" \"https://api.greynoise.io/v3/community/1.2.3.4\""),
		],
		links=[("GreyNoise", "https://viz.greynoise.io"), ("Signup", "https://www.greynoise.io/signup")]),
	dict(icon="👽", name="OTX AlienVault", domain="otx.alienvault.com", cat="cyber",
		tags=["cyber", "api"],
		desc="Open Threat Exchange. 200K+ partecipanti, pulse di intelligence IOC. API gratuita completa.",
		methods=[
			("WEB", "Dashboard", "otx.alienvault.com → crea account gratuito → cerca IP/domain/hash → Pulse correlati, reputazione.", ""),
			("API", "API DirectConnect (gratuita)", "Sostituisci \"IPv4\" con \"domain\", \"file\", \"url\" o \"hostname\".",
				"curl -H \"X-OTX-API-KEY: KEY\" \"https://otx.alienvault.com/api/v1/indicators/IPv4/1.2.3.4/general\""),
			("DOWNLOAD", "Subscribe ai Pulse", "Sottoscrivi pulse per feed automatici → integra con SIEM via OTX-Python:",
				"pip install OTXv2"),
		],
		links=[("OTX", "https://otx.alienvault.com"), ("API", "https://otx.alienvault.com/api")]),
	dict(icon="🔭", name="SecurityTrails (free)", domain="securitytrails.com", cat="cyber",
		tags=["cyber", "api"],
		desc="DNS history, IP history, WHOIS, subdomains. 50 req/mese gratuiti. Essenziale per infra investigation.",
		methods=[
			("WEB", "Ricerca dominio", "securitytrails.com → inserisci dominio → DNS history, IP associati, subdomini, WHOIS. Parzialmente gratuito senza login.", ""),
			("API", "API (50 req/mese gratis)", "Registrati → ottieni API key gratuita. /subdomains per lista subdomini.",
				"curl -H \"APIKEY: YOUR_KEY\" \"https://api.securitytrails.com/v1/domain/example.com/dns/a\""),
		],
		links=[("SecurityTrails", "https://securitytrails.com"), ("API", "https://docs.securitytrails.com")]),
	dict(icon="🌐", name="ViewDNS.info", domain="viewdns.info", cat="cyber",
		tags=["cyber", "api"],
		desc="15+ tool DNS gratuiti: IP History, Reverse IP, WHOIS, Reverse WHOIS, DNS lookup, Port scan, IP geolocation.",
		methods=[
			("WEB", "Strumenti web", "viewdns.info → scegli tool: \"IP History\" → IP storici di un dominio. \"Reverse IP\" → tutti i domini su un IP. \"Reverse Whois\" → tutti i domini di un registrante.", ""),
			("API", "API (gratuita 250 req/giorno)", "Chiave gratuita su viewdns.info/api.",
				"curl \"https://api.viewdns.info/iphistory/?domain=example.com&apikey=YOUR_KEY&output=json\""),
		],
		links=[("ViewDNS", "https://viewdns.info"), ("API Key", "https://viewdns.info/api/")]),
	dict(icon="🗺", name="DNSDumpster", domain="dnsdumpster.com", cat="cyber",
		tags=["cyber"],
		desc="Mapping completo infrastruttura DNS: subdomini, MX, TXT, NS, IP, banner. Gratuito senza login.",
		methods=[
			("WEB", "Ricerca", "dnsdumpster.com → inserisci dominio → mappa visuale infrastruttura + tabella dati + export XLSX.", ""),
		],
		links=[("DNSDumpster", "https://dnsdumpster.com")]),

	# ---------- BREACH ----------
	dict(icon="💀", name="Have I Been Pwned", domain="haveibeenpwned.com", cat="breach",
		tags=["breach", "cyber", "api"],
		desc="14 miliardi di record da 700+ breach. Verifica email/phone compromessi. API $3.50/mese (web gratuito).",
		methods=[
			("WEB", "Verifica Email/Phone", "haveibeenpwned.com → inserisci email → lista breach immediata. /passwords → verifica hash password.", ""),
			("API", "API v3 (gratis per Pwned Passwords)", "Password hash check GRATUITO → k-anonymity, nessuna chiave necessaria.",
				"curl https://api.pwnedpasswords.com/range/5BAA6 | grep \"1E4C9\""),
			("CLI", "CLI Python", "",
				"pip install pwnedpasswords-api\npython -c \"import pwnedpasswords; print(pwnedpasswords.check('password123'))\""),
		],
		links=[("HIBP", "https://haveibeenpwned.com"), ("API Key", "https://haveibeenpwned.com/API/Key"), ("Pwned Passwords", "https://haveibeenpwned.com/Passwords")]),
	dict(icon="🗃", name="Intelligence X (free tier)", domain="intelx.io", cat="breach",
		tags=["breach", "cyber", "social"],
		desc="Dark+clear web, paste, breach, Tor, I2P. Tier gratuito molto limitato ma utile per verifiche rapide.",
		methods=[
			("WEB", "Ricerca gratuita", "intelx.io → inserisci email/dominio/IP/Bitcoin addr → risultati limitati senza account.", ""),
			("API", "API (gratuita limitatissima)", "Dopo registrazione:",
				"curl -H \"x-key: KEY\" \"https://2.intelx.io/intelligent/search?q=target@email.com&maxresults=5\""),
		],
		links=[("IntelX", "https://intelx.io"), ("Signup", "https://intelx.io/signup")]),

	# ---------- CRYPTO ----------
	dict(icon="₮", name="TronScan", domain="tronscan.org", cat="crypto",
		tags=["crypto", "api"],
		desc="Explorer ufficiale TRON. Wallet, transazioni USDT TRC-20, smart contract, token, staking. Essenziale per mandati crypto.",
		methods=[
			("WEB", "Lookup wallet", "tronscan.org/#/address/WALLET → saldo, transazioni TRC-20 USDT, token, storico completo. Zero login.", ""),
			("API", "API REST (gratuita)", "JSON con bilancio, transazioni.",
				"curl \"https://apilist.tronscanapi.com/api/accountv2?address=TWALLETADDRESS\"\ncurl \"https://apilist.tronscanapi.com/api/transaction?sort=-timestamp&count=true&limit=50&address=WALLET\""),
		],
		links=[("TronScan", "https://tronscan.org"), ("API", "https://docs.tronscan.org")]),
	dict(icon="Ξ", name="Etherscan", domain="etherscan.io", cat="crypto",
		tags=["crypto", "api"],
		desc="Explorer ETH + ERC-20 token. Wallet, TX, smart contract, internal transactions. API gratuita 5 req/sec.",
		methods=[
			("WEB", "Lookup wallet/TX", "etherscan.io → inserisci address/TX hash/block → dati completi, token transfers, internal TXs.", ""),
			("API", "API (gratuita 5 req/sec)", "Registrati → ottieni API key gratuita. Tutte le TX ERC-20:",
				"curl \"https://api.etherscan.io/api?module=account&action=tokentx&address=WALLET&startblock=0&endblock=99999999&sort=asc&apikey=KEY\""),
		],
		links=[("Etherscan", "https://etherscan.io"), ("API Key", "https://etherscan.io/apis"), ("Docs", "https://docs.etherscan.io")]),
	dict(icon="🍞", name="Breadcrumbs", domain="breadcrumbs.app", cat="crypto",
		tags=["crypto"],
		desc="Tracing wallet BTC/ETH a grafo. Visualizzazione connessioni, clustering, flow analysis. Base gratuita.",
		methods=[
			("WEB", "Ricerca wallet", "Registrati su breadcrumbs.app/register (gratuito) → inserisci address → grafo transazioni → identifica cluster e exchange known.", ""),
			("WEB", "Analisi cluster", "Nel grafo: click nodo → \"Investigate\" → espandi transazioni correlate → tieni traccia del flow. Esporta PNG del grafo.", ""),
		],
		links=[("Breadcrumbs", "https://www.breadcrumbs.app"), ("Register", "https://www.breadcrumbs.app/register")]),
	dict(icon="₿", name="OXT — Bitcoin OSINT", domain="oxt.me", cat="crypto",
		tags=["crypto"],
		desc="Bitcoin OSINT avanzato. Clustering address, privacy analysis, heuristics CIOH, CISHA. Gratuito.",
		methods=[
			("WEB", "Address analysis", "oxt.me/address/BITCOIN_ADDR → cluster, entity detection, transaction graph. Nessun login.", ""),
			("WEB", "Transaction graph", "oxt.me/transaction/TXID → visual flow inputs/outputs → identifica mixing e peel chain.", ""),
		],
		links=[("OXT", "https://oxt.me")]),
	dict(icon="📊", name="Blockchain.com Explorer", domain="blockchain.com/explorer", cat="crypto",
		tags=["crypto", "api"],
		desc="Explorer Bitcoin primario. Wallet, TX, blocks. API gratuita.",
		methods=[
			("WEB", "Lookup", "blockchain.com/explorer → inserisci BTC address/TX hash → balance, TX list.", ""),
			("API", "API Blockchain.info", "JSON con balance, n_tx, transazioni. Nessuna autenticazione.",
				"curl \"https://blockchain.info/rawaddr/BITCOIN_ADDRESS\""),
		],
		links=[("Explorer", "https://www.blockchain.com/explorer"), ("API", "https://www.blockchain.com/explorer/api")]),

	# ---------- GEO ----------
	dict(icon="🌍", name="Google Earth Pro", domain="earth.google.com", cat="geo",
		tags=["geo"],
		desc="Immagini satellitari storiche e attuali. Timeline slider per confronto temporale. Misure distanza/area. Gratuito.",
		methods=[
			("DOWNLOAD", "Download (desktop)", "google.com/earth/about/versions → installa su Windows/Mac/Linux → accesso gratuito completo.", ""),
			("WEB", "Web version", "earth.google.com/web → versione browser. Timeline: View → Historical Imagery → slider temporale → confronto prima/dopo.", ""),
			("CLI", "Export KML", "File → Export → KML/KMZ → apri in QGIS o importa in Maltego per analisi geospaziale.", ""),
		],
		links=[("Web", "https://earth.google.com/web"), ("Desktop", "https://www.google.com/earth/about/versions/")]),
	dict(icon="🛰", name="Sentinel Hub EO Browser", domain="apps.sentinel-hub.com/eo-browser", cat="geo",
		tags=["geo", "api"],
		desc="Immagini satellite Sentinel ESA gratuite. Multispettrale, SAR, analisi NDVI, confronto temporale. Piano free disponibile.",
		methods=[
			("WEB", "EO Browser", "apps.sentinel-hub.com/eo-browser → registrati gratis → seleziona area → scegli satellite (Sentinel-1 SAR, Sentinel-2 ottico) → timeline.", ""),
			("API", "API (trial gratuito)", "sentinel-hub.com/trial → 30 giorni trial API → Processing API per richieste satellitari programmatiche.", ""),
		],
		links=[("EO Browser", "https://apps.sentinel-hub.com/eo-browser/"), ("Trial", "https://www.sentinel-hub.com/trial")]),
	dict(icon="🗺", name="OpenStreetMap + Overpass API", domain="openstreetmap.org", cat="geo",
		tags=["geo", "api"],
		desc="Mappa mondiale open. Overpass API per query geografiche: trova edifici, strade, POI per coordinate o area.",
		methods=[
			("WEB", "Mappe", "openstreetmap.org → naviga mappa → click oggetto → dati JSON. Ricerca: Nominatim → geocoding gratuito.", ""),
			("API", "Overpass API (query geospaziali)", "Es. tutte le banche in area Milano:",
				"curl \"https://overpass-api.de/api/interpreter?data=[out:json];node[name~'Banca'][amenity=bank](45.4,9.0,45.5,9.3);out;\""),
			("API", "Nominatim Geocoding", "Coordinate GPS da indirizzo:",
				"curl \"https://nominatim.openstreetmap.org/search?q=via+montenapoleone+milano&format=json\""),
		],
		links=[("OSM", "https://www.openstreetmap.org"), ("Overpass", "https://overpass-turbo.eu"), ("Nominatim", "https://nominatim.openstreetmap.org")]),
	dict(icon="📷", name="Mapillary — Street Level", domain="mapillary.com", cat="geo",
		tags=["geo"],
		desc="Immagini street-level crowdsourced globali. Fotografie georeferenziate. Alternativa a Google Street View con più copertura rurale.",
		methods=[
			("WEB", "Browse", "mapillary.com/app → naviga mappa → clicca foto → visualizza street-level con metadata (data, utente, camera).", ""),
			("API", "API v4 (gratuita)", "Immagini nell'area con coordinate:",
				"curl \"https://graph.mapillary.com/images?access_token=TOKEN&bbox=9.1,45.4,9.2,45.5&limit=100\""),
		],
		links=[("Mapillary", "https://www.mapillary.com/app"), ("API", "https://www.mapillary.com/developer/api-documentation")]),
	dict(icon="☀", name="SunCalc", domain="suncalc.org", cat="geo",
		tags=["geo"],
		desc="Calcola posizione sole e ombre per data/luogo. Utile per geoverifica foto/video (shadow analysis OSINT).",
		methods=[
			("WEB", "Calcolo", "suncalc.org → clicca su mappa → seleziona data/ora → vedi azimut/elevazione sole e direzione ombre. Verifica se ombre foto corrispondono.", ""),
		],
		links=[("SunCalc", "https://suncalc.org")]),

	# ---------- TRASPORTI ----------
	dict(icon="🚢", name="MarineTraffic", domain="marinetraffic.com", cat="trasporti",
		tags=["trasporti"],
		desc="Tracking navi real-time via AIS. Rotte, porto di partenza/arrivo, speed, flag, ownership. Piano base gratuito.",
		methods=[
			("WEB", "Tracking real-time", "marinetraffic.com → mappa interattiva → click nave → IMO, MMSI, flag, rotta, ETA. Cerca per nome/IMO nella barra.", ""),
			("WEB", "Ricerca storica (limitata)", "Profilo nave → \"Voyage History\" → ultime posizioni disponibili (storico limitato in free). Per full history serve piano a pagamento.", ""),
		],
		links=[("MarineTraffic", "https://www.marinetraffic.com"), ("Vessel Search", "https://www.marinetraffic.com/en/data/?asset_type=vessels")]),
	dict(icon="🛳", name="VesselFinder", domain="vesselfinder.com", cat="trasporti",
		tags=["trasporti"],
		desc="Tracking navi real-time AIS. Alternativa e complementare a MarineTraffic. Database IMO, bandiere, armatori.",
		methods=[
			("WEB", "Tracking", "vesselfinder.com → cerca per nome/IMO/MMSI → posizione, rotta, port calls. Incrocia con MarineTraffic per verificare dati AIS.", ""),
			("WEB", "Photo database", "shipspotting.com → foto nave per IMO → utile per identificazione visiva e verifica flag.", ""),
		],
		links=[("VesselFinder", "https://www.vesselfinder.com"), ("ShipSpotting", "https://www.shipspotting.com")]),
	dict(icon="⚓", name="Equasis — Ship Safety", domain="equasis.org", cat="trasporti",
		tags=["trasporti"],
		desc="Database ufficiale sicurezza nave. Ownership, gestione, ispezioni PSC, deficienze, detentions. Gratuito con registrazione.",
		methods=[
			("WEB", "Registrazione e ricerca", "Registrati GRATIS su equasis.org → cerca per IMO/nome → armatore, manager, flag history, ispezioni PSC, detentions.", ""),
			("CLI", "CLI tool", "",
				"pip install equasis\npython -c \"from equasis import EquasisClient; c=EquasisClient('email','pass'); print(c.get_ship_infos('1234567'))\""),
		],
		links=[("Equasis", "https://www.equasis.org"), ("Python CLI", "https://pypi.org/project/equasis/")]),
	dict(icon="✈", name="FlightRadar24 (free)", domain="flightradar24.com", cat="trasporti",
		tags=["trasporti"],
		desc="Tracking aeromobili real-time via ADS-B. Identificazione voli, rotte, registrazioni. Piano free disponibile.",
		methods=[
			("WEB", "Tracking live", "flightradar24.com → mappa → click aeromobile → numero volo, registrazione, rotta, quota, velocità, origine/destinazione.", ""),
			("WEB", "Ricerca per registrazione", "Barra di ricerca → inserisci tail number (es. I-AIGE) → storico voli limitato in free. Per full history: FlightAware o ADS-B Exchange.", ""),
		],
		links=[("FlightRadar24", "https://www.flightradar24.com"), ("ADSB Exchange", "https://globe.adsbexchange.com")]),
	dict(icon="🛩", name="OpenSky Network", domain="opensky-network.org", cat="trasporti",
		tags=["trasporti", "api"],
		desc="Database ADS-B open-source. Storico voli completo e gratuito con API. Non-profit accademico.",
		methods=[
			("WEB", "Explorer", "opensky-network.org → inserisci ICAO hex o registrazione → storico voli.", ""),
			("API", "REST API (gratuita con account)", "JSON storico voli per periodo:",
				"curl -u \"user:pass\" \"https://opensky-network.org/api/flights/aircraft?icao24=3c6444&begin=1672531200&end=1672617600\""),
		],
		links=[("OpenSky", "https://opensky-network.org"), ("API", "https://openskynetwork.github.io/opensky-api/"), ("Signup", "https://opensky-network.org/index.php?option=com_users&view=registration")]),
	dict(icon="📡", name="ADS-B Exchange", domain="adsbexchange.com", cat="trasporti",
		tags=["trasporti", "api"],
		desc="Feed ADS-B non filtrato (include voli militari/privati). Nessuna censura su richiesta governi. API gratuita limitata.",
		methods=[
			("WEB", "Live map", "globe.adsbexchange.com → mappa live → include voli censurati da FR24. Filtra per tipo/paese/altitudine.", ""),
			("API", "API (gratuita 1 req/sec)", "Dati aeromobile per registrazione. Quota gratuita RapidAPI.",
				"curl \"https://adsbexchange-com1.p.rapidapi.com/v2/registration/N12345/\" -H \"X-RapidAPI-Key: FREE_KEY\""),
		],
		links=[("Globe", "https://globe.adsbexchange.com"), ("API", "https://www.adsbexchange.com/data/")]),

	# ---------- SOCIAL ----------
	dict(icon="🐦", name="Sherlock — Username Hunt", domain="github.com/sherlock-project/sherlock", cat="social",
		tags=["social", "persone", "api"],
		desc="Ricerca username su 400+ piattaforme contemporaneamente. CLI Python open source. Gratuito.",
		methods=[
			("CLI", "Installazione e uso", "Lista URL su ogni social trovato. Output JSON disponibile.",
				"pip install sherlock-project\nsherlock --timeout 10 username_target\nsherlock username --output risultato.json"),
			("CLI", "Maigret (avanzato)", "3000+ siti + analisi profilo automatica, report HTML.",
				"pip install maigret\nmaigret username_target --all-sites"),
		],
		links=[("Sherlock", "https://github.com/sherlock-project/sherlock"), ("Maigret", "https://github.com/soxoj/maigret")]),
	dict(icon="🦉", name="Holehe — Email to Social", domain="github.com/megadose/holehe", cat="social",
		tags=["social", "persone"],
		desc="Verifica se un'email è registrata su 120+ servizi (Twitter, Instagram, Facebook, ecc.). CLI Python.",
		methods=[
			("CLI", "Installazione e uso", "Lista servizi dove l'email è registrata. Usa \"is_registered\": true per positivi.",
				"pip install holehe\nholehe target@email.com"),
			("CLI", "Output JSON", "Solo servizi positivi in JSON per post-processing.",
				"holehe target@email.com --only-used --output json"),
		],
		links=[("Holehe", "https://github.com/megadose/holehe")]),
	dict(icon="🔎", name="GHunt — Google Account OSINT", domain="github.com/mxrch/ghunt", cat="social",
		tags=["social", "persone"],
		desc="Da email Gmail: estrae nome, Google ID, foto, Maps reviews, servizi Google collegati, attività pubblica.",
		methods=[
			("CLI", "Installazione", "Segui la procedura OAuth Google, poi profilo Google completo.",
				"pip install ghunt\nghunt login\nghunt email target@gmail.com"),
			("CLI", "Output", "Estrae: display name, photo URL, Google Maps reviews, YouTube channel, Google Calendar (pubblico), Hangouts status.", ""),
		],
		links=[("GHunt", "https://github.com/mxrch/ghunt")]),

	# ---------- IMMAGINI ----------
	dict(icon="🔍", name="ExifTool — Metadata", domain="exiftool.org", cat="immagini",
		tags=["immagini", "geo"],
		desc="Legge/scrive metadati EXIF/IPTC/XMP da immagini, video, documenti. GPS, timestamp, camera, author. CLI gratuito.",
		methods=[
			("CLI", "Installazione", "Linux: apt-get install libimage-exiftool-perl. Windows: scarica .exe da exiftool.org. Mac:",
				"brew install exiftool"),
			("CLI", "Estrazione dati", "Tutti i metadati / solo GPS / batch CSV:",
				"exiftool image.jpg\nexiftool -gpslatitude -gpslongitude image.jpg\nexiftool -csv *.jpg > metadata.csv"),
			("WEB", "Web alternativa", "metadata2go.com oppure Jeffrey's Exif Viewer → upload immagine → metadati online.", ""),
		],
		links=[("ExifTool", "https://exiftool.org"), ("Web Viewer", "https://www.metadata2go.com")]),
	dict(icon="🧪", name="FotoForensics", domain="fotoforensics.com", cat="immagini",
		tags=["immagini"],
		desc="Analisi forensica immagini: Error Level Analysis (ELA), noise analysis, clone detection. Verifica manipolazioni. Gratuito.",
		methods=[
			("WEB", "Upload analisi", "fotoforensics.com → upload immagine o URL → seleziona analisi (ELA, Hash, Metadata, Luminance Gradient) → identifica zone editate.", ""),
			("WEB", "Alternativa: Forensically", "29a.ch/photo-forensics → tool browser-based con ELA, clone detection, JPEG analysis, più completo di FotoForensics.", ""),
		],
		links=[("FotoForensics", "https://fotoforensics.com"), ("Forensically", "https://29a.ch/photo-forensics/")]),
	dict(icon="👁", name="TinEye — Reverse Image", domain="tineye.com", cat="immagini",
		tags=["immagini", "persone"],
		desc="Reverse image search per trovare la fonte originale di un'immagine e tutte le sue copie online. 60+ miliardi di immagini indicizzate.",
		methods=[
			("WEB", "Upload/URL", "tineye.com → upload foto o incolla URL immagine → risultati ordinati per \"best match\" o \"oldest\" per trovare originale.", ""),
			("WEB", "Incrociare con Google/Bing", "Google Images: drag&drop → reverse search. Bing Visual Search: bing.com/visualsearch. Yandex: spesso migliore per volti est-europei.", ""),
		],
		links=[("TinEye", "https://tineye.com"), ("Google Images", "https://images.google.com"), ("Yandex Images", "https://yandex.com/images/")]),

	# ---------- GIUDIZIARIO ----------
	dict(icon="⚖", name="PACER — US Courts", domain="pacer.gov", cat="giudiziario",
		tags=["giudiziario"],
		desc="Tutti i procedimenti federali USA. Cause civili, penali, fallimentari. $0.10/pagina (gratuito sotto $30/trimestre).",
		methods=[
			("WEB", "Registrazione e ricerca", "Registrati su pacer.uscourts.gov/register-account → gratis. Poi: PCL search → cerca per nome → lista casi. Sotto $30/trimestre = gratuito effettivo.", ""),
			("WEB", "CourtListener (gratuito completo)", "courtlistener.com → mirror gratuito di PACER. Ricerca full-text + API REST gratuita.",
				"curl \"https://www.courtlistener.com/api/rest/v3/dockets/?q=company+name&court=ca1\""),
		],
		links=[("PACER", "https://pacer.uscourts.gov"), ("CourtListener", "https://www.courtlistener.com"), ("API CL", "https://www.courtlistener.com/help/api/rest/")]),
	dict(icon="🚔", name="Interpol Red Notices", domain="interpol.int", cat="giudiziario",
		tags=["giudiziario", "sanzioni"],
		desc="Ricerca soggetti ricercati internazionalmente. Notice pubbliche: rosso (wanted), giallo (missing), arancio (threats).",
		methods=[
			("WEB", "Ricerca diretta", "interpol.int/notices → filtra per nazionalità, sesso, età → schede con foto e accuse. Zero registrazione.", ""),
			("API", "Via OpenSanctions (aggregato)", "OpenSanctions integra tutte le notice Interpol pubbliche.",
				"curl \"https://api.opensanctions.org/search/default?q=mario+rossi&schema=Person&datasets=interpol_red_notices&api_key=KEY\""),
		],
		links=[("Red Notices", "https://www.interpol.int/How-we-work/Notices/Red-Notices/View-Red-Notices"), ("Yellow Notices", "https://www.interpol.int/How-we-work/Notices/Yellow-Notices/View-Yellow-Notices")]),
	dict(icon="🇮🇹", name="Gazzetta Ufficiale Italia", domain="gazzettaufficiale.it", cat="giudiziario",
		tags=["giudiziario", "aziende"],
		desc="Procedure concorsuali, aste giudiziarie, provvedimenti, sentenze. Archivio dal 1861. Full-text search.",
		methods=[
			("WEB", "Ricerca", "gazzettaufficiale.it/ricercaArticolo → inserisci CF/P.IVA o ragione sociale → trova procedure concorsuali e provvedimenti.", ""),
			("API", "API (sperimentale)", "JSON documenti GU. Documentazione limitata.",
				"curl \"https://api.gazzettaufficiale.it/v1/gazzettaufficiale/search?q=ragione+sociale&type=5\""),
		],
		links=[("GU", "https://www.gazzettaufficiale.it"), ("Aste PVP", "https://pvp.giustizia.it")]),

	# ---------- IMMOBILI ----------
	dict(icon="🏠", name="Agenzia Entrate — Catasto", domain="agenziaentrate.gov.it", cat="immobili",
		tags=["immobili"],
		desc="Visure catastali, planimetrie, ipoteche, rendite. Asset tracing immobiliare ITA. Gratuito con SPID.",
		methods=[
			("WEB", "Consultazione online", "Portale ADE → accedi con SPID → Catasto → inserisci CF → lista immobili con dati catastali.", ""),
			("WEB", "SISTER (professionisti)", "Registrati su sister.agenziaentrate.gov.it → accesso professionale a visure catastali e ipotecarie per CF/soggetto terzo.", ""),
		],
		links=[("ADE Catasto", "https://www.agenziaentrate.gov.it"), ("SISTER", "https://sister.agenziaentrate.gov.it")]),

	# ---------- MEDIA ----------
	dict(icon="📦", name="Wayback Machine", domain="web.archive.org", cat="media",
		tags=["media", "persone", "cyber"],
		desc="Archivio web storico 1996-oggi. Recupero siti eliminati, versioni precedenti. Fondamentale per digital forensics.",
		methods=[
			("WEB", "Lookup URL", "web.archive.org → inserisci URL → calendario snapshot → seleziona data → naviga versione storica.", ""),
			("API", "Availability API", "Snapshot più vicino alla data:",
				"curl \"https://archive.org/wayback/available?url=example.com&timestamp=20200101\""),
			("API", "CDX API (tutti gli snapshot)", "Lista timestamp/URL di tutti gli snapshot:",
				"curl \"http://web.archive.org/cdx/search/cdx?url=example.com&output=json&limit=100&from=20190101&to=20201231\""),
		],
		links=[("Wayback", "https://web.archive.org"), ("CDX API", "https://archive.org/developers/wayback-cdx-server.html")]),
	dict(icon="🗞", name="Google News + Alerts", domain="news.google.com", cat="media",
		tags=["media", "api"],
		desc="Motore news globale + alert gratuiti automatici. Operatori booleani avanzati. RSS disponibile.",
		methods=[
			("WEB", "Ricerca avanzata", "news.google.com → cerca: \"Mario Rossi\" (frode OR truffa OR indagini) after:2023-01-01. Filtra per paese e lingua.", ""),
			("WEB", "Alert automatici", "google.com/alerts → crea alert per nome soggetto → frequenza \"Immediate\" → email su ogni nuova notizia. Genera anche RSS.", ""),
			("API", "SerpAPI (piano free)", "Tier gratuito (100 search/mese) per Google News:",
				"curl \"https://serpapi.com/search.json?q=mario+rossi+indagini&tbm=nws&api_key=KEY\""),
		],
		links=[("Google News", "https://news.google.com"), ("Alerts", "https://www.google.com/alerts")]),
	dict(icon="📦", name="Archive.org — Web Archive", domain="web.archive.org", cat="media",
		tags=["media", "cyber", "api"],
		desc="Archivio storico web dal 1996. Recupero siti eliminati, prove digitali. CDX API per ricerca bulk snapshot.",
		methods=[
			("WEB", "Lookup", "web.archive.org → URL → calendario snapshot → naviga versione storica.", ""),
			("API", "CDX API (bulk snapshots)", "Tutti gli snapshot JSON:",
				"curl \"http://web.archive.org/cdx/search/cdx?url=dominio.com&output=json&limit=1000&from=20190101\""),
			("API", "Availability API", "Snapshot più vicino:",
				"curl \"https://archive.org/wayback/available?url=dominio.com&timestamp=20200601120000\""),
		],
		links=[("Archive", "https://archive.org"), ("CDX API", "https://archive.org/developers/wayback-cdx-server.html")]),
	dict(icon="🕷", name="CommonCrawl", domain="commoncrawl.org", cat="media",
		tags=["media", "api"],
		desc="Petabyte di crawl web pubblici scaricabili. Per ricerca pattern, link analysis, domain intelligence a scala.",
		methods=[
			("DOWNLOAD", "Download dati", "commoncrawl.org/get-started → indici mensili su S3 AWS:",
				"aws s3 ls s3://commoncrawl/cc-index/table/cc-main/"),
			("API", "CC Index API", "Tutti gli URL indicizzati del dominio:",
				"curl \"https://index.commoncrawl.org/CC-MAIN-2024-10-index?url=*.dominio.com&output=json\""),
		],
		links=[("CommonCrawl", "https://commoncrawl.org"), ("Index Search", "https://index.commoncrawl.org")]),

	# ---------- GOVDATA ----------
	dict(icon="🇪🇺", name="data.europa.eu — EU Open Data", domain="data.europa.eu", cat="govdata",
		tags=["govdata", "api"],
		desc="Portal dati aperti UE. 1M+ dataset: sanzioni, aziende, contratti pubblici, statistiche, sentenze.",
		methods=[
			("WEB", "Ricerca dataset", "data.europa.eu/data/datasets → cerca per keyword → scarica CSV/JSON/XML.", ""),
			("API", "SPARQL Endpoint", "Dati strutturati EU via SPARQL:",
				"curl \"https://data.europa.eu/sparql?query=SELECT+?s+?p+?o+WHERE+{?s+?p+?o}+LIMIT+10&format=json\""),
		],
		links=[("EU Data", "https://data.europa.eu"), ("API", "https://data.europa.eu/en/about/api")]),
	dict(icon="🇮🇹", name="data.gov.it — Open Data Italia", domain="dati.gov.it", cat="govdata",
		tags=["govdata", "api"],
		desc="Portale open data italiano. Dati PA, contratti pubblici, statistiche, territorio.",
		methods=[
			("WEB", "Ricerca", "dati.gov.it → cerca per tema → download CSV/JSON/RDF.", ""),
			("API", "CKAN API", "Metadati dataset JSON:",
				"curl \"https://www.dati.gov.it/api/action/package_search?q=contratti+pubblici&rows=10\"\ncurl \"https://www.dati.gov.it/api/action/resource_show?id=RESOURCE_ID\""),
		],
		links=[("Dati.gov.it", "https://dati.gov.it"), ("CKAN API", "https://docs.ckan.org/en/latest/api/")]),
	dict(icon="📋", name="OpenTender — EU Public Procurement", domain="opentender.eu", cat="govdata",
		tags=["govdata", "aziende", "api"],
		desc="Appalti pubblici EU. Chi vince gare pubbliche per paese, settore, importo. Incrocia con indagini su aziende.",
		methods=[
			("WEB", "Ricerca appalti", "opentender.eu → seleziona paese → cerca per nome azienda → storico gare vinte, importi, committente.", ""),
			("API", "API REST", "JSON con appalti filtrati:",
				"curl \"https://opentender.eu/api/v1/tender/search?q=company+name&filters[country]=IT&size=10\""),
			("DOWNLOAD", "Download bulk", "opentender.eu/download → dataset CSV per paese completo.", ""),
		],
		links=[("OpenTender", "https://opentender.eu"), ("API", "https://opentender.eu/about/how-it-works")]),
	dict(icon="🇪🇺", name="TED — Tenders Electronic Daily", domain="ted.europa.eu", cat="govdata",
		tags=["govdata", "aziende"],
		desc="Gazzetta Ufficiale UE per appalti pubblici. Tutti i bandi sopra soglia UE. API e bulk download.",
		methods=[
			("WEB", "Ricerca bandi", "ted.europa.eu → cerca per aggiudicatario/paese/settore → storico gare e importi.", ""),
			("API", "TED API v3", "Registra API key gratis su TED Developer.",
				"curl \"https://api.ted.europa.eu/v3/notices/search?q=winner-name:azienda&scope=active&fields=winner-name,award-value,buyer-name&limit=10\" -H \"apiKey: FREE_KEY\""),
		],
		links=[("TED", "https://ted.europa.eu"), ("API", "https://docs.ted.europa.eu")]),
	dict(icon="🌐", name="World Bank Open Data", domain="data.worldbank.org", cat="govdata",
		tags=["govdata", "finanza", "api"],
		desc="Dati economici e finanziari mondiali. PIL, debito, inflazione, governance, corruzione index. API gratuita.",
		methods=[
			("API", "API REST", "PIL Italia per anno / Control of Corruption globale:",
				"curl \"https://api.worldbank.org/v2/country/IT/indicator/NY.GDP.MKTP.CD?format=json\"\ncurl \"https://api.worldbank.org/v2/country/all/indicator/CC.EST?format=json\""),
			("WEB", "Data Explorer", "data.worldbank.org → seleziona indicatore → scarica CSV/Excel.", ""),
		],
		links=[("World Bank", "https://data.worldbank.org"), ("API", "https://datahelpdesk.worldbank.org/knowledgebase/topics/125589")]),
]


def get_context(context):
	if frappe.session.user == "Guest":
		frappe.local.flags.redirect_location = "/login?redirect-to=/portal/osint/fonti"
		raise frappe.Redirect

	context.no_cache = 1
	context.categories = CATEGORIES
	context.fonti = FONTI
	context.total = len(FONTI)
	cat_map = {key: (icon, label) for key, icon, label in CATEGORIES}
	context.grouped = [
		(key, icon, label, [f for f in FONTI if f["cat"] == key])
		for key, icon, label in CATEGORIES
	]
	context.cat_map = cat_map
